/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyNewRouteImport } from './routes/verify-new'
import { Route as VerifyExistingRouteImport } from './routes/verify-existing'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const VerifyNewRoute = VerifyNewRouteImport.update({
  id: '/verify-new',
  path: '/verify-new',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyExistingRoute = VerifyExistingRouteImport.update({
  id: '/verify-existing',
  path: '/verify-existing',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/verify-existing': typeof VerifyExistingRoute
  '/verify-new': typeof VerifyNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/verify-existing': typeof VerifyExistingRoute
  '/verify-new': typeof VerifyNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/verify-existing': typeof VerifyExistingRoute
  '/verify-new': typeof VerifyNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/get-started'
    | '/login'
    | '/register'
    | '/verify'
    | '/verify-existing'
    | '/verify-new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/get-started'
    | '/login'
    | '/register'
    | '/verify'
    | '/verify-existing'
    | '/verify-new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/get-started'
    | '/login'
    | '/register'
    | '/verify'
    | '/verify-existing'
    | '/verify-new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  GetStartedRoute: typeof GetStartedRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  VerifyRoute: typeof VerifyRoute
  VerifyExistingRoute: typeof VerifyExistingRoute
  VerifyNewRoute: typeof VerifyNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-new': {
      id: '/verify-new'
      path: '/verify-new'
      fullPath: '/verify-new'
      preLoaderRoute: typeof VerifyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-existing': {
      id: '/verify-existing'
      path: '/verify-existing'
      fullPath: '/verify-existing'
      preLoaderRoute: typeof VerifyExistingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  GetStartedRoute: GetStartedRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  VerifyRoute: VerifyRoute,
  VerifyExistingRoute: VerifyExistingRoute,
  VerifyNewRoute: VerifyNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
